Dek 4 als bezoeker wil ik een account kunnen aanmaken zodat ik kan sporten bij de kast. back end issue
AngelovanOsch1/DeKast pull request #4
Opened 2023-09-15 07:10 UTC by kitobirdies

2023-09-15 08:27 UTC, AngelovanOsch1 commented on DeKast/package.json
Haal bootcrap eruit en uninstall deze shit

2023-09-15 08:27 UTC, AngelovanOsch1 commented on DeKast/src/app/app.component.html
> -<h1>TEST</h1>
Haal test dingen eruit

2023-09-15 08:28 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.scss
> +    margin-bottom: 10px;
schrijf al de padding en margin heel uit uit dus margin: 0 0 0 0;

2023-09-15 08:30 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.ts
> +    if (this.registrationForm.valid) {
haal de console logs eruit en de alert shit. Kun je proberen Register met Firebase te doen? Alleen email and password moet, dus je hoeft geen collection te maken

2023-09-15 08:31 UTC, AngelovanOsch1 reviewed
lees de comments

2023-09-15 10:14 UTC, AngelovanOsch1 requested changes

2023-09-15 10:14 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.ts
> +      this.toastService.show('Form is not valid. Please check the fields.');
Maak hier Nederlands text van

2023-09-15 10:14 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.scss
> +    font-size: 12px;
fontsize moet REM unit zijn en niet px unit

2023-09-15 10:14 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.html
> +
kun je al de for attribute uit de form halen. Dit is echt niet nodig

2023-09-15 10:14 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.html
> +      <h3 class="mb-1">Register</h3>
Haal boolcrap eruit als je het niet gebruikt.

2023-09-18 18:58 UTC, AngelovanOsch1 requested changes

2023-09-18 18:58 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.html
> +      <div class="mb-3">
mb-3 class doet niks toch? Aangezien je bootstrap eruit hebt gehaald. Doe dit dan wel overal waar je bootcrap hebt gebruikt.

2023-09-18 18:58 UTC, AngelovanOsch1 commented on DeKast/src/app/register/register.component.html
> +        <label for="email" class="form-label">Email:</label>
typical GPT code. idk for attribute is echt cancer. Kun je dit overal waar dit wordt gebruikt eruit halen?

2023-09-18 19:04 UTC, kitobirdies commented on DeKast/src/app/register/register.component.scss
> +    margin-bottom: 10px;
personal prefference

2023-09-19 08:24 UTC, AngelovanOsch1 approved these changes

2023-09-19 08:25 UTC, merged